### ISSUE TITLE
 _add_transactions() fails on master and latest tag

### ISSUE THREAD

**Issue by noamelf** [rienafairefr/pynYNAB#36]
Hi,
First of all, thanks a lot for creating this package! It's really helpful for automation. 

Running the csvimport script fails with this message on master branch and `0.5` tag: 
```Traceback (most recent call last):
  File "csvimport.py", line 186, in <module>
    csvimport_main()
  File "csvimport.py", line 42, in csvimport_main
    do_csvimport(args)
  File "csvimport.py", line 182, in do_csvimport
    client.add_transactions(transactions)
  File "/home/noam/projects/open-source/pynYNAB/pynYNAB/Client.py", line 339, in add_transactions
    self._add_transactions(chunkelement)
TypeError: _add_transactions() takes exactly 2 arguments (1 given)          
```

Reverting to `0.4.3` solves the problem, so I guess it's some commit in between.

**Comment by rienafairefr** [comment]
Sorry, the csvimport is kinda unused so it lagged behind the rest of the
library. I'll look into it

On Mar 24, 2017 23:00, "Noam Elfanbaum" <notifications@github.com> wrote:

Hi,
First of all, thanks a lot for creating this package! It's really helpful
for automation.

Running the csvimport script fails with this message on master branch and
0.5 tag:

  File "csvimport.py", line 186, in <module>
    csvimport_main()
  File "csvimport.py", line 42, in csvimport_main
    do_csvimport(args)
  File "csvimport.py", line 182, in do_csvimport
    client.add_transactions(transactions)
  File "/home/noam/projects/open-source/pynYNAB/pynYNAB/Client.py",
line 339, in add_transactions
    self._add_transactions(chunkelement)
TypeError: _add_transactions() takes exactly 2 arguments (1 given)

Reverting to 0.4.3 solves the problem, so I guess it's some commit in
between.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rienafairefr/pynYNAB/issues/36>, or mute the thread

**Comment by rienafairefr** [comment]
Hey @noamelf, can you check back on the status of this ? I just reorganised the way the scripts are invoked are transactions pushed, I think there should be no problem now, with latest master b714999

**Comment by noamelf** [comment]
Hi, thanks that was quick!
I got 2 errors while rerunning it. The first:
`ImportError: No module named ofxtools` 

After installing `ofxtools`, I run it again and received:
`No handlers could be found for logger "pynYNAB.__main__"`

**Comment by chbndrhnns** [comment]
@noamelf: I had the same issue but you could try again now as some fixes were made.
